### ISSUE TITLE
proxy.component.scss exceed maximum budget when build

### ISSUE THREAD

**Issue by manng2** [HaasStefan/tailwind-microfrontends#1]
With this approach, when we build the MFE, the `proxy.component.scss` file exceeds the maximum budget. Can we increase the limit? If the budget is exceeded, will it affect performance?

<img width="1412" alt="image" src="https://github.com/HaasStefan/tailwind-microfrontends/assets/44439173/21b91277-71b5-4122-a6c3-7aab1abb5da0">

**Comment by HaasStefan** [comment]
Sure, you can increase it in the project.json file under budget. But yeah, it is definitely a small performance hit since you need to load a big css again with duplication... 

Microfrontends are not easy.
